### ISSUE TITLE
Different scaling behaviour in 1.14.0

### ISSUE THREAD

**Issue by jcavar** [ordo-one/package-benchmark#222]
Hello,

Thank you for this amazing package!

It seems that scaling behaviour has changed in https://github.com/ordo-one/package-benchmark/commit/0b15255d21fabe55bc67a34d167f1ed5e51f9af1.

New logic scales results if `scale == false`. This is different to before and seems semantically incorrect, but I see the change is applied in few places.

I am happy to open PR, but wanted to check if this is intentional first?

**Comment by hassila** [comment]
Hi, thanks - yes this is intentional - see release note here:

https://github.com/ordo-one/package-benchmark/releases/tag/1.14.0

Basically there was much confusion of not scaling to the inner loop count so we decided to change the default - you can still get the non-scaled result by specifying --scale (so, yes, we intentionally did flip the behavior, sorry!)

**Comment by jcavar** [comment]
Gotcha, thank you!
